#pragma once
#include "aradani.h"
#define მოხსენი R
#define მიადგიn An
#define ჩაახვიე P
#define ჩჩაახვიე PP
#define ჩჩჩაახვიე PPP
#define ჩჩჩჩაახვიე PPPP
#define ამოახვიე U                
#define აამოახვიე UU
#define ააამოახვიე UUU
#define აააამოახვიე UUUU
#define ამოხიე D
#define ამოოხიე DD
#define ამოოოხიე DDD
#define ამოოოოხიე DDDD
#define ამოოოოოხიე DDDDD
#define და da
#define ან an
#define ანდა anda
#define არადანი aradani
#define მიადგი A
#define მიადგი2 A2
#define მიადგი3 A3
#define მიადგი4 A4
#define მიადგი5 A5
#define მიადგი6 A6
#define მიადგი7 A7
#define მიადგი8 A8
#define მიადგი9 A9
#define მიადგი10 A10
#define მიადგი11 A11
#define მიადგი12 A12
#define მიადგი13 A13
#define მიადგი14 A14
#define მიადგი15 A15
#define მიადგი16 A16
#define მიადგი17 A17
#define მიადგი18 A18
#define მიადგი19 A19
#define მიადგი20 A20
